apiVersion: v1
kind: Service
metadata:
  name: github-pages
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: dcruzf.github.io
  ports:
    - port: 80
    protocol: TCP
      targetPort: 80
