site_name: /home
site_description: "dcruzf"
repo_url: https://github.com/dcruzf
repo_name: dcruzf
docs_dir: dcruzf

theme:
  name: material
  icon: assets/images/delta.svg
  logo: assets/images/delta.svg
  favicon: assets/images/delta.svg
  custom_dir: overrides

  font:
    text: Noto Sans Mono
    code: Noto Sans Mono

  features:
    - content.code.copy
#    - navigation.drawer
#    - navigation.instant
#    - navigation.instant.progress
#    - navigation.tracking
#    - navigation.hide
#    - toc.follow
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: black

plugins:
  - privacy

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: monokai


extra:
  generator: false

extra_css:
  - assets/extra_css/extra.css

nav:
  - index.md