site_name: /home/dcruzf
site_description: "dcruzf"
repo_url: https://github.com/dcruzf
repo_name: dcruzf
docs_dir: dcruzf

theme:
  name: material
  icon: assets/images/delta.svg
  logo: assets/images/delta.svg
  favicon: assets/images/delta.svg
  custom_dir: overrides

  font:
    text: Noto Sans Mono
    code: Noto Sans Mono

  features:
#    - navigation.drawer
#    - navigation.instant
#    - navigation.instant.progress
#    - navigation.tracking
#    - navigation.hide
#    - toc.follow
    
  palette:
    - media: "(prefers-color-scheme: light)"
      
      scheme: slate
      primary: black
      accent: black

plugins:
  - privacy

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

extra:
  generator: false

extra_css:
  - assets/extra_css/extra.css


nav:
  - index.md